### ISSUE TITLE
Client Error: Bad Request

### ISSUE THREAD

**Issue by dabest1** [soymsk/rundeck_history_purge_tool#1]
Thanks for sharing your tool, but I am not able to run it. I am getting an exception as shown below. What version of Python are you using? Also you README shows an incorrect example usage with "-s 10" parameters, which are not available.

$ python --version
Python 2.7.12
$ python /var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py -t mytoken myproject -m 100 -j myjob
Args:
        max_delete_size: 100
        dry_run: False
        project: myproject
        host: localhost
        keep_history_size: 20
        chunk_size: 20
        job_filter: myjob
        port: 4440
Traceback (most recent call last):
  File "/var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py", line 127, in <module>
    args.dry_run
  File "/var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py", line 51, in purge_history
    total = get_history_total(client, project, job_filter)
  File "/var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py", line 38, in get_history_total
    history = search_history(client, project, job_filter)
  File "/var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py", line 24, in search_history
    res = client.get(request)
  File "/var/lib/rundeck/rundeck_history_purge_tool/rd_purge_history.py", line 102, in get
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 683, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

**Comment by dabest1** [comment]
I was able to make it work by modifying the API version, since my Rundeck only supports API version up to 17.
In rd_purge_history.py file, I modified this line from:
`API_VERSION = 18`
to:
`API_VERSION = 17`

Then the tool was running, but it was not deleting anything. It turned out that I need to grant ACL permission for allowing deletion through API.
More info is available here: http://rundeck.org/2.6.9/api/index.html#delete-an-execution
Here is an example of how I modified a part of /etc/rundeck/apitoken.aclpolicy by adding delete_execution action:
```
description: API Application level access control
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] # allow read of system info
  project:
    - match:
        name: '.*'
      allow: [read] # allow view of all projects
    - match:
        name: 'myproject'
      allow: [read, delete_execution] # allow view of all projects
  storage:
    - match:
        path: '(keys|keys/.*)'
      allow: '*' # allow all access to manage stored keys
by:
  group: api_token_group
```
